
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daqgpikubcdzsgusjcqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhcWdwaWt1YmNkenNndXNqY3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjIxNDcsImV4cCI6MjA1ODc5ODE0N30.Pzp6Rj4owrqN0vxegpnDMV04mmCCUAx64SmsDol5q2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Export URL and key for edge functions
export const EDGE_FUNCTION_URL = `${SUPABASE_URL}/functions/v1`;
